version: "3"

services:
  full-33-app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/opt/app/src
    environment:
      - PORT=5000
      - DATABASE=postgres://postgres:piaus123@full-33-postgres:5432/full-33
    depends_on:
      - full-33-postgres
  full-33-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=piaus123
      - POSTGRES_DB=full-33
    logging:
      driver: none
  full-33-adminer:
    image: adminer
    ports:
      - 8080:8080
